[package]
edition = "2018"
name = "next-swc"
version = "0.0.0"
publish = false

[features]
plugin = ["turbopack-binding/__swc_core_binding_napi_plugin"]

[dependencies]
chrono = "0.4.38"
convert_case = "0.7.0"
easy-error = "1.0.0"
either = "1.11.0"
fxhash = "0.2.1"
hex = "0.4.3"
once_cell = { workspace = true }
next-transform-font = {workspace = true}
pathdiff = "0.2.1"
regex = "1.10.4"
rustc-hash = "2.0.0"
serde = "1.0.200"
serde_json = "1.0.116"
sha1 = "0.10.6"
tracing = { version = "0.1.40" }

turbopack-binding = { workspace = true, features = [
  "__swc_core",
  "__swc_core_next_core",
  "__swc_transform_styled_jsx",
  "__swc_transform_emotion",
  "__swc_transform_styled_components",
  "__swc_transform_modularize_imports",
  "__swc_transform_relay",
] }

[dev-dependencies]
turbopack-binding = { workspace = true, features = [
  "__swc_core_testing_transform",
  "__swc_testing",
] }

walkdir = "2.5.0"
